[package]
name = "database"
version = "0.0.1"
edition = "2021"

[lib]
name = "database"
path = "src/lib.rs"

[dependencies]
tokio-postgres = "0.7.8"
tokio = { version = "1", features = ["full"] }
config = { path = "../config"}